# Use DecapBridge PKCE auth (required)
backend:
  name: git-gateway
  repo: anasthmi/cafe-ami
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/0e402e0a-4b92-4d1b-880b-a44be46948f1/pkce
  auth_token_endpoint: /sites/0e402e0a-4b92-4d1b-880b-a44be46948f1/token
  gateway_url: https://gateway.decapbridge.com

  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://anasthmi.github.io/cafe-ami

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "daily_menu"
    label: "Daily Menu"
    file: "data/daily-menu.json"
    fields:
      - { label: "Date", name: "date", widget: "string", default: "Today's Specials" }
      - { label: "Soup / Starter", name: "starter", widget: "string" }
      - { label: "Main Course 1", name: "main1", widget: "string" }
      - { label: "Main Course 1 Price", name: "price1", widget: "string" }
      - { label: "Main Course 2", name: "main2", widget: "string" }
      - { label: "Main Course 2 Price", name: "price2", widget: "string" }
      - { label: "Dessert of the Day", name: "dessert", widget: "string" }
